news_blog/blog/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('post_detail/<slug:slug>', views.post_detail, name='post_detail_url'),
    path('category_detail/<slug:slug>', views.category_detail, name='category_detail_url'),
    path('search', views.search, name='search'),
    path('register', views.register, name='register'),
    path('login', views.login_site, name='login_site'),
    path('log_out', views.logout_site, name='logout_site'),
    path('post_detail/<slug:slug>/comment', views.comment, name='comment'),
]

news_blog/news_blog/urls.py
import stat
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_blog/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    title = models.CharField("Название", max_length=255)
    image = models.ImageField('Картинка', upload_to='category_image/')
    slug = models.SlugField('Ссылка', unique=True)

    def __str__(self):
        return self.title

    def get_link(self):
        return reverse('category_detail_url', kwargs={'slug': self.slug})
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


    
class Post(models.Model):
    title = models.CharField('Заголовок', max_length=255)
    text = models.TextField('Содержание')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, null= True, blank= True)
    image = models.ImageField('Картинка поста', upload_to="post_image/")
    date = models.DateTimeField('Дата создания поста', default=timezone.now)
    slug = models.SlugField('Ссылка', unique=True)
    view = models.IntegerField('Просмотры', default=0)
    
    def __str__(self):
        return self.title

    def get_link(self):
        return reverse('post_detail_url', kwargs={'slug': self.slug})
    
    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.post.title + ' ' + self.author.username
    
    class Meta:
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарии'

news_blog/blog/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Логин', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Логин"}))
    password1 = forms.CharField(label='Пароль', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control mb-3', 'placeholder':"Пароль"}))
    password2 = forms.CharField(label='Повторите пароль', required=True, widget=forms.PasswordInput(attrs={'class': 'form-control mb-3', 'placeholder':"Повторите пароль"}))
    email = forms.EmailField(label='почта', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Почта"}))
    first_name = forms.CharField(label='Имя', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Имя"}))
    last_name = forms.CharField(label='Фамилия', required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder':"Фамилия"}))

    class Meta:
        model = User
        fields = ('username', 'email' , 'password1' , 'password2' , 'first_name' , 'last_name')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
            return user

news_blog/blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category, Comment
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm
from django.urls import reverse


def index(request):
    posts = Post.objects.order_by('-date')[:10]
    recommendations = Post.objects.filter(view__gte=100)[:3]
    categoies = Category.objects.all()
    context = {
        'posts': posts,
        'categories': categoies,
        'recommendations': recommendations
        }
    return render(request, 'index.html', context)

def post_detail(request, slug):
    post = Post.objects.get(slug__exact=slug)
    post.view += 1
    post.save()
    return render(request, 'post_detail.html', {'post':post})

def category_detail(request, slug):
     category = Category.objects.get(slug__exact=slug)
     return render(request, 'category_detail.html', {'category':category})
def search(request):
    query = request.GET.get('search')
    posts = Post.objects.filter(Q(title__iregex = query))
    content = {'posts': posts, "query":query}
    return render(request, 'search.html', content)

def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return redirect('index')
        else:
            form = RegisterForm()
        return render(request, 'register.html', {'form': form})
    return redirect('index')


def login_site(request):
    if request.user.is_authenticated:
        return redirect('index')
    message = None
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            message = 'Извините такого пользователя нет'
            return render(request, 'login.html', {'message': message})
    return render(request, 'login.html', {'message': message})

def logout_site(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('index')

def comment(request, slug):
    post = Post.objects.get(slug__exact = slug)
    if request.method == 'POST':
        comment = Comment()
        comment.author = request.user
        post = Post.objects.get(slug__exact = slug)
        comment.post = Post.objects.get(slug__exact=slug)
        comment.text = request.POST.get('text')
        comment.save()
        return redirect(reverse('post_detail_url', kwargs={'slug': slug}))
    return redirect(reverse('post_detail_url', kwargs={'slug': slug}))

news_blog/blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} {% endblock %} </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
    <body>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register'%}">Регистрация</a>
              </li>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login_site'%}">Вход</a>
            </li>
            {% else %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout_site'%}">Выход</a>
          </li>
          {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" action="{% url 'search' %}">
              <input name="search" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    <div class="bg"></div>
    <div style="height: 1000px;">
        {% block content %}
        {% endblock %}
    </div>
    <div class="bg"></div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html> 

news_blog/blog/templates/category_detail.html
{% extends 'base.html' %}
{% block title%}
{{category.title}}
{% endblock %}
{% block content %}
<div class="container">
    <h1 class="text-center line">{{category.title}}</h1>
</div>
<div class="container">
    <h1 class="line">Новости</h1>
     <div class="row row-cols-1 mt-3 row-cols-md-5 g-3">
        {% for post in category.post_set.all %}
        <div class="col" >
          <div class="card" style="min-height: 650px; border-radius: 25px;">
            <a href="{{post.get_link}}">
            <img src="{{post.image.url}}" style="border-radius: 25px; height: 300px; object-fit: cover;" class="card-img-top" alt="...">
          </a>
            <div class="card-body">
              <h5 class="card-title"><a href="{{post.get_link}}">{{post.title}}</a></h5>
              <p class="card-text"><a href="{{post.get_link}}">{{post.text|slice:'0:200'}}...</a></p>
              <p class="text-end">{{post.date|date:'d-F-Y'}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
{% endblock %}

news_blog/blog/templates/index.html
{% extends 'base.html' %}
{% block title %}
Главная страница
{% endblock %}
{% block content %}
<div class="container">
  <h1 class="line">Новости</h1>
   <div class="row row-cols-1 mt-3 row-cols-md-5 g-3">
      {% for post in posts %}
      <div class="col" >
        <div class="card" style="min-height: 650px; border-radius: 25px;">
          <a href="{{post.get_link}}">
          <img src="{{post.image.url}}" style="border-radius: 25px; height: 300px; object-fit: cover;" class="card-img-top" alt="...">
        </a>
          <div class="card-body">
            <h5 class="card-title"><a href="{{post.get_link}}">{{post.title}}</a></h5>
            <p class="card-text"><a href="{{post.get_link}}">{{post.text|slice:'0:200'}}...</a></p>
            <p class="text-end">{{post.date|date:'d-F-Y'}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <h1 class="line">Категории</h1>
      <div class="row mt-3 row-cols-1 row-cols-md-5 g-4">
         {% for category in categories %}
         <div class="col">
           <div class="card cover-card">
            <a href="{{category.get_link}}">
              <img src="{{category.image.url}}" class="card-img-top cover-img" style="height: 100px; object-fit: cover;" alt="...">
            </a>
             <div class="card-body">
               <h5 class="card-title" style="text-align: center;"><a href="{{category.get_link}}">{{category.title}}</a></h5>
             </div>
           </div>
         </div>
         {% endfor %}
      </div>
      <div class="row row-cols-1 mt-3 row-cols-md-5 g-3">
        {% for rec in recommendations %}
        <div class="col" >
          <div class="card" style="min-height: 650px; border-radius: 25px;">
            <a href="{{rec.get_link}}">
            <img src="{{rec.image.url}}" style="border-radius: 25px; height: 300px; object-fit: cover;" class="card-img-top" alt="...">
          </a>
            <div class="card-body">
              <h5 class="card-title"><a href="{{rec.get_link}}">{{rec.title}}</a></h5>
              <p class="card-text"><a href="{{rec.get_link}}">{{rec.text|slice:'0:200'}}...</a></p>
              <p class="text-end">{{rec.date|date:'d-F-Y'}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
</div>
{% endblock %}

news_blog/blog/templates/login.html
{% extends 'base.html' %}
{% block title %}
Главная страница
{% endblock %}
{% block content %}
    <div class="container">
        <form action="{% url 'login_site'%}" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="Логин" class="form-control, mb-2" name="username">
            <input type="text" placeholder="Паоль" class="form-control, mb-2" name="password">
            <button>Войти</button>
        </form>
    </div>
{% endblock %}

news_blog/blog/templates/post_detail.html
{% extends 'base.html' %}
{% block title%}
{{post.title}}
{% endblock %}
{% block content%}
<div class="container">
    <div class="border-dashed">
    <h2 class="text-center">{{post.title}}</h2>
    <img src="{{post.image.url}}" alt="" class="post-image">
    <p>
        {{post.text}}
    </p>
    <p class="text-end">{{post.date|date:'d-F-Y'}}</p>
    <p class="text-end">Комментариев: {{post.comment_set.count}} Просмотры: {{post.view}}</p>
    {% if request.user.is_authenticated %}
    <form action="{% url 'comment' post.slug %}" method="POST">
        {% csrf_token %}
        <textarea name="text" id="" cols="30" rows="10"></textarea>
        <button>Отправить</button>
    </form>
    {% else %}
    <p>Что бы написать комментарий вы должны <a href="{% url 'login_site' %}">Войти</a>или <a href="{% url 'register' %}">Зарегистрироваться</a>
    </p>
    {% endif %}
    <div class="row row-cols-1 row-cols-md-1 g-4">
        {% for comment in post.comment_set.all %}
        <div class="col">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{comment.author.username}}</h5>
              <p class="card-text">{{comment.text}}</p>
              <p class="card-text">{{comment.date|date:'d-F-Y'}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    
    </div>
</div>
{% endblock %}

news_blog/blog/templates/register.html
{% extends 'base.html' %}
{% block title %}
Главная страница
{% endblock %}
{% block content %}
    <div class="container">
        <form action="{% url 'register' %}" method="POST">
            {% csrf_token %}
            {% for f in form%}
                {{f}}
            {% endfor %}
            <button class="btn btn-primary">Регистрация</button>
        </form>
    </div>
{% endblock %}

news_blog/blog/templates/search.html
{% extends 'base.html' %}
{% block title %}
Главная страница
{% endblock %}
{% block content %}
<div class="container">
  <h1 class="line">Новости</h1>
   <div class="row row-cols-1 mt-3 row-cols-md-5 g-3">
      {% for post in posts %}
      <div class="col" >
        <div class="card" style="min-height: 650px; border-radius: 25px;">
          <a href="{{post.get_link}}">
          <img src="{{post.image.url}}" style="border-radius: 25px; height: 300px; object-fit: cover;" class="card-img-top" alt="...">
        </a>
          <div class="card-body">
            <h5 class="card-title"><a href="{{post.get_link}}">{{post.title}}</a></h5>
            <p class="card-text"><a href="{{post.get_link}}">{{post.text|slice:'0:200'}}...</a></p>
            <p class="text-end">{{post.date|date:'d-F-Y'}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}